### ISSUE TITLE
这个能用在RN上么

### ISSUE THREAD

**Issue by orzhtml** [lyxia/LYXRefreshProject#1]

**Comment by lyxia** [comment]
不能 这个是原生测试




    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            
                            
                            
                                
                                    邮箱：liuyunxia8@gmail.com
                                
                        
                    
                
            
        
    


签名由 网易邮箱大师 定制
在2018年03月26日 11:52，Carson Chen 写道： 

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/lyxia/LYXRefreshProject","title":"lyxia/LYXRefreshProject","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/lyxia/LYXRefreshProject"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"这个能用在RN上么 (#1)"}],"action":{"name":"View Issue","url":"https://github.com/lyxia/LYXRefreshProject/issues/1"}}}
